#!/bin/bash

EWW="/usr/bin/eww"  # Adjust this path to the location of your eww binary
CFG="/home/nix/.config/eww/dashboard"
FILE="/tmp/eww_opened"

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    ${EWW} --config "$CFG" open-many \
        background \
        profile \
        system \
        clock \
        uptime \
        music \
        github \
        reddit \
        twitter \
        youtube \
        weather \
        apps \
        mail \
        logout \
        sleep \
        reboot \
        poweroff \
        folders
else
    ${EWW} --config "$CFG" close-all
    rm "$FILE"
fi